# Site
repository: bsridatta/bsridatta.github.io
#repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)

# favicon: images/favicon.ico
# redirect_to:
#   - https://www.linkedin.com/in/sridatta/
# Personal info
name: Sri Datta Budaraju
title: YACSG - Yet Another Computer Science Guy 
email: b.sridatta@gmail.com
Mobile : +076-965 65 35 

# Social links
github_username:  bsridatta
linkedin_username: sridatta
twitter_username: BSridatta
facebook_username: sridatta.budaraju
# dribbble_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sri Datta and I'm a Computer Science masters student at KTH Royal Institute of Technology, Sweden. 
  I consider myself a curious person and have experimented with different areas in Computer Science from Android Development to Sensor Technology.
  I pretty much loved "everything" that I did but at the bottom of my heart, I love Physics and the way it teaches us about nature.
  Like many of you reading this I wanted to see what this "AI" is about. 
  Thanks to Andrew NG's DeepLearning.ai and Siraj Raval's motivational videos, 
  I was so fascinated by the scope of its applications and I immediately packed my bags to Stockholm to get really involved.
  Now I spend the majority of my time doing very interesting courses at KTH and working on an autonomous F1 car at KTH Formula Student.
  

# projects_title: Projects


# Experience Section



# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Deep Learning and Autonomous Systems, some of my other interests and hobbies are:
   - Watching Movies
   - Listening to Music
   - Admiring the beauty of nature
   
  If you have anything in common, Do ping me. I'd love to have a chat with people like you ;)
 
 
# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from

